#!/bin/bash

count_age=0
count_name=0
ltage=0
eqage=0
gtage=0
k=0
m=0
n=0

if [ -n "$(echo "$1" | grep ^[0-9][0-9]*$)" ];then
  target_age=$1
  echo "Target age is ${target_age}."
else
  exit 1
fi

echo  "Please input your name: "
read name

if [ -z "$name" ];then
    exit 1
fi

for name_1 in $name;do
    total_name[$count_name]=$name_1
    count_name=`expr $count_name + 1`
done

echo  "Please input your age: "
read age

for age_1 in $age;do
    total_age[$count_age]=$age_1
    count_age=`expr $count_age + 1`
done

if [ -n "$(echo "${age}" | grep [0-9][0-9]*$)" ];then
    for (( i=0;i<${#total_age[@]};i++ ));do
	for((j=${#total_age[@]}-1;j>i;j--));do
	    if [ ${total_age[j]} -lt ${total_age[j-1]} ];then
		    t=${total_age[j]}
		    total_age[j]=${total_age[j-1]}
		    total_age[j-1]=$t

		    temp=${total_name[j]}
		    total_name[j]=${total_name[j-1]}
		    total_name[j-1]=$temp
	    fi
	done
    done
    
		  
    if [ $count_name == $count_age ];then
        i=0
	while [ ${i} -lt ${count_age} ];do
	    if [ ${total_age[$i]} -lt ${target_age} ];then
		lt_age[$ltage]=${total_age[$i]};
		lt_name[$ltage]=${total_name[$i]};
		ltage=`expr $ltage + 1`
	    elif [ ${total_age[$i]} -eq $target_age ];then
		eq_age[$eqage]=${total_age[$i]};
		eq_name[$eqage]=${total_name[$i]};
		eqage=`expr $eqage + 1`
	    else
		gt_age[$gtage]=${total_age[$i]};
		gt_name[$gtage]=${total_name[$i]};
		gtage=`expr $gtage + 1`
	    fi
	    i=`expr $i + 1`
	done

        echo "年龄小于目标年龄的：" 
	while [ ${k} -lt ${count_age} ];do
	    if [ ${total_age[$k]} -lt ${target_age} ];then
	     echo "name="${total_name[$k]}",age="${total_age[$k]}""
	    fi
	    k=`expr $k + 1`    
	done
      
        echo "年龄等于目标年龄的：" 
	while [ ${m} -lt ${count_age} ];do
	    if [ ${total_age[$m]} -eq ${target_age} ];then
	     echo "name="${total_name[$m]}",age="${total_age[$m]}""
	    fi
	    m=`expr $m + 1`
	done

        echo "年龄大于目标年龄的："	
	while [ ${n} -lt ${count_age} ];do
	    if [ ${total_age[$n]} -gt ${target_age} ];then
		
	        echo "name="${total_name[$n]}",age="${total_age[$n]}""
	    fi
	    n=`expr $n + 1`
        done
	    
    else
	echo "name and age not match"
	exit 1
    fi
else
    echo "Invalidate age"
    exit 1
fi

exit 0
